# Generated by Django 5.2.6 on 2025-10-01 11:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('mrn', models.CharField(blank=True, max_length=50, verbose_name='Hospital No / IPD No')),
                ('reg_no', models.CharField(blank=True, max_length=50)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('bed', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, help_text='GENERAL / DELUXE / PRIVATE etc.', max_length=100)),
                ('doctor', models.CharField(blank=True, max_length=200)),
                ('admit_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='billing.admission')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type', models.CharField(choices=[('PROC', 'Procedure / OT / Surgeon'), ('INV', 'Investigation / Lab / USG / X-Ray'), ('BED', 'Bed Charges / Room Rent'), ('CONS', 'Consultation'), ('PHARM', 'Pharmacy'), ('NURS', 'Nursing / General'), ('COMP', 'Compulsory / Registration'), ('ER', 'Emergency / Casualty')], max_length=5)),
                ('particulars', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sac_code', models.CharField(blank=True, max_length=20)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.admission')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=30)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_bill', to='billing.admission')),
            ],
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
