# Generated by Django 5.2.6 on 2025-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_admission_advancepayment_chargeitem_finalbill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepayment',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='finalbill',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='receipt_no',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='ref_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Reference / Receipt No'),
        ),
        migrations.AddField(
            model_name='finalbill',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
