# Generated by Django 5.2.6 on 2026-03-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hms.doctor'),
            preserve_default=False,
        ),
    ]
