# Generated by Django 5.2.6 on 2026-03-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
