# Generated by Django 5.2.6 on 2026-03-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_appointment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='hms.department')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='signs',
            field=models.ManyToManyField(blank=True, to='hms.sign'),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='hms.department')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='hms.symptom'),
        ),
    ]
