# Generated by Django 5.2.6 on 2026-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_sign_consultation_signs_symptom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmaster',
            name='category',
            field=models.CharField(choices=[('General Surgery', 'General Surgery'), ('Obstetrics & Gynecology', 'Obstetrics & Gynecology'), ('Orthopedics', 'Orthopedics')], default='General Surgery', max_length=100),
        ),
    ]
