# Generated by Django 5.2.6 on 2026-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_alter_drugmaster_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigationparameter',
            options={'ordering': ['investigation', 'order']},
        ),
        migrations.RemoveField(
            model_name='investigationparameter',
            name='normal_range',
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='critical_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='critical_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='female_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='male_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='result_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('pos_neg', 'Positive / Negative'), ('reactive', 'Reactive / Non-Reactive'), ('text', 'Text')], default='numeric', max_length=20),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='show_in_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investigationparameter',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='investigationparameter',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
