# Generated by Django 5.2.6 on 2026-03-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_alter_investigationparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigationresult',
            options={'ordering': ['parameter__order']},
        ),
        migrations.AlterField(
            model_name='investigationresult',
            name='entered_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='investigationresult',
            name='value',
            field=models.CharField(help_text='Result value entered by lab technician', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='investigationresult',
            unique_together={('bill_item', 'parameter')},
        ),
    ]
