# Generated by Django 5.2.6 on 2026-03-06 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0009_alter_investigationresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('USG', 'Ultrasound'), ('ENDOSCOPY', 'Endoscopy'), ('OT', 'Operation Theatre'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(help_text='Example: Chest X-Ray PA View', max_length=200)),
                ('image', models.ImageField(upload_to='medical_images/')),
                ('report_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='hms.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
