# Generated by Django 5.2.6 on 2026-03-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_alter_medicalimage_image_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_images', to='hms.consultation'),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='image_type',
            field=models.CharField(choices=[('XRAY', 'X-Ray'), ('USG', 'Ultrasound (USG)'), ('ENDOSCOPY', 'Endoscopy'), ('OT', 'OT Image'), ('ECG', 'ECG'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('OTHER', 'Other')], default='XRAY', max_length=50),
        ),
    ]
