# Generated by Django 5.2.6 on 2026-03-07 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0013_bed_ward_ipdadmission_bed_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='attendant_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='attendant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='attendant_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.doctor'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='icd_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='ipd_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='admission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.bed'),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.ward'),
        ),
    ]
