# Generated by Django 5.2.6 on 2026-03-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_ipdadmission_attendant_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.ipdadmission')),
            ],
        ),
    ]
