# Generated by Django 5.2.6 on 2026-03-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0015_ipdvital'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.department'),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
