# Generated by Django 5.2.6 on 2026-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0016_ipdadmission_department_alter_ipdadmission_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
    ]
