# Generated by Django 5.2.6 on 2026-03-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0017_ipdadmission_symptoms_ipdadmission_treatment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.ipdadmission')),
            ],
        ),
    ]
