# Generated by Django 5.2.6 on 2026-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0018_ipdmedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='condition_at_discharge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='course_in_hospital',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='discharge_advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='discharge_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='procedure_done',
            field=models.TextField(blank=True),
        ),
    ]
