# Generated by Django 5.2.6 on 2026-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0024_remove_dischargebillitem_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargebill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dischargebill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargebill',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('FREE', 'Free of Cost')], max_length=20, null=True),
        ),
    ]
