# Generated by Django 5.2.6 on 2026-03-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0025_dischargebill_is_paid_dischargebill_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargebill',
            name='original_advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
