# Generated by Django 5.2.6 on 2026-03-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0026_dischargebill_original_advance_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargebill',
            name='original_advance_paid',
        ),
        migrations.AddField(
            model_name='ipdadvance',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ipdadvance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hms.patient'),
        ),
        migrations.AlterField(
            model_name='ipdadvance',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('FREE', 'Free of Cost')], default='CASH', max_length=20),
        ),
    ]
