# Generated by Django 5.2.6 on 2026-03-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0027_remove_dischargebill_original_advance_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
