# Generated by Django 5.2.6 on 2026-03-17 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0028_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ['category__dept_code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='investigationbill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='investigationcategory',
            options={'ordering': ['dept_code', 'name'], 'verbose_name': 'Investigation Category', 'verbose_name_plural': 'Investigation Categories'},
        ),
        migrations.AddField(
            model_name='investigationbill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationbill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investigationbill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investigationcategory',
            name='dept_code',
            field=models.CharField(choices=[('RADIOLOGY', 'Radiology'), ('HISTOPATHOLOGY', 'Histopathology'), ('BIOCHEMISTRY', 'Biochemistry'), ('HEMATOLOGY', 'Hematology'), ('MICROBIOLOGY', 'Microbiology'), ('ECG', 'ECG'), ('ENDOSCOPY', 'Endoscopy & Procedures'), ('OTHER', 'Other')], default='OTHER', help_text='Used in reports for department-wise billing summary.', max_length=20),
        ),
        migrations.AlterField(
            model_name='investigationbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investigationcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
