# Generated by Django 5.2.6 on 2026-03-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0029_alter_investigation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('FREE', 'Free')], default='CASH', max_length=10),
        ),
    ]
