# Generated by Django 5.2.6 on 2026-03-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0030_appointment_fee_appointment_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABDMConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=100, unique=True)),
                ('patient_abha', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('DENIED', 'Denied')], default='GRANTED', max_length=20)),
                ('hi_types', models.TextField(blank=True)),
                ('artifact', models.TextField(blank=True)),
                ('date_from', models.CharField(blank=True, max_length=50)),
                ('date_to', models.CharField(blank=True, max_length=50)),
                ('expire_at', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ABDM Consent',
                'verbose_name_plural': 'ABDM Consents',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ABDMCareContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=255)),
                ('hi_type', models.CharField(choices=[('OPDischargeNote', 'OPD Consultation'), ('DiagnosticReport', 'Lab Report'), ('Prescription', 'Prescription'), ('DischargeSummary', 'Discharge Summary')], default='OPDischargeNote', max_length=50)),
                ('linked', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_contexts', to='hms.patient')),
            ],
            options={
                'verbose_name': 'Care Context',
                'verbose_name_plural': 'Care Contexts',
                'unique_together': {('patient', 'reference_number')},
            },
        ),
    ]
