# Generated by Django 5.2.6 on 2026-03-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0031_abdmconsent_abdmcarecontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(max_length=20)),
                ('surgeon', models.CharField(max_length=100)),
                ('assistant', models.CharField(blank=True, max_length=100, null=True)),
                ('anesthetist', models.CharField(max_length=100)),
                ('procedure', models.CharField(max_length=200)),
                ('ot_date', models.DateField()),
                ('ot_time', models.TimeField()),
                ('ot_room', models.CharField(max_length=50)),
                ('case_type', models.CharField(choices=[('Elective', 'Elective'), ('Emergency', 'Emergency')], max_length=20)),
                ('anesthesia_type', models.CharField(choices=[('GA', 'GA'), ('SA', 'SA'), ('LA', 'LA')], max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OTNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('findings', models.TextField()),
                ('procedure_done', models.TextField()),
                ('complications', models.TextField(blank=True, null=True)),
                ('blood_loss', models.CharField(blank=True, max_length=50)),
                ('post_op_condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms.otbooking')),
            ],
        ),
    ]
