# Generated by Django 5.2.6 on 2026-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0032_otbooking_otnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otbooking',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
