# Generated by Django 5.2.6 on 2026-03-21 10:06

import hms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0034_inventoryitem_supplier_stockout_stockin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('doctor', 'Doctor'), ('staff', 'Staff'), ('equipment', 'Equipment AMC / Certificate')], max_length=20)),
                ('doc_type', models.CharField(choices=[('hospital_certification', 'Hospital Certification'), ('pollution_noc', 'Pollution NOC'), ('bmw_udyog', 'BMW / Udyog Certificate'), ('clinical_establishment', 'Clinical Establishment Certificate'), ('fire_noc', 'Fire NOC'), ('hospital_pan', 'Hospital PAN Card'), ('bank_details', 'Bank Details Document'), ('other_hospital', 'Other'), ('doctor_aadhaar', 'Aadhaar Card'), ('doctor_pan', 'PAN Card'), ('medical_council', 'Medical Council Certificate'), ('abdm_doctor', 'Professional Health ID (ABDM)'), ('other_doctor', 'Other'), ('staff_aadhaar', 'Aadhaar Card'), ('staff_pan', 'PAN Card'), ('degree_certificate', 'Degree Certificate'), ('nursing_certificate', 'Nursing Certificate'), ('abdm_staff', 'Professional Health ID (ABDM)'), ('other_staff', 'Other'), ('xray', 'X-Ray'), ('carm', 'C-ARM'), ('lab_machine', 'Lab Machine'), ('anaesthetic_machine', 'Anaesthetic Machine'), ('ecg', 'ECG Machine'), ('defibrillator', 'Defibrillator'), ('ot_light', 'OT Light'), ('autoclave', 'Autoclave'), ('other_equipment', 'Other Equipment')], max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('person_name', models.CharField(blank=True, help_text='Doctor or staff member name', max_length=150, null=True)),
                ('equipment_name', models.CharField(blank=True, help_text='Equipment name / serial number', max_length=150, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Issuing Authority')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=hms.models.document_upload_path, verbose_name='Upload File (PDF / Image)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Document',
                'verbose_name_plural': 'Hospital Documents',
                'ordering': ['category', 'expiry_date'],
            },
        ),
    ]
