# Generated by Django 5.2.6 on 2026-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0035_hospitaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
