# Generated by Django 5.2.6 on 2026-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0036_consultation_ai_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='last_modified_by',
        ),
        migrations.AddField(
            model_name='consultation',
            name='advice',
            field=models.TextField(blank=True),
        ),
    ]
