# Generated by Django 5.2.6 on 2026-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0037_remove_consultation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='loinc_panel_code',
            field=models.CharField(blank=True, help_text="LOINC panel code e.g. '58410-2' for CBC", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='loinc_code',
            field=models.CharField(blank=True, help_text="LOINC code e.g. '718-7' for Haemoglobin", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investigationparameter',
            name='loinc_display',
            field=models.CharField(blank=True, help_text="LOINC display name e.g. 'Hemoglobin [Mass/volume] in Blood'", max_length=100, null=True),
        ),
    ]
