# Generated by Django 5.2.6 on 2026-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0038_investigation_loinc_panel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdcode',
            name='snomed_code',
            field=models.CharField(blank=True, help_text="SNOMED CT concept ID e.g. '73211009' for Diabetes mellitus", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='icdcode',
            name='snomed_description',
            field=models.CharField(blank=True, help_text="SNOMED CT preferred term e.g. 'Diabetes mellitus'", max_length=255, null=True),
        ),
    ]
