# Generated by Django 5.2.6 on 2026-03-28 08:26

import django.utils.timezone
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0039_icdcode_snomed_code_icdcode_snomed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_type',
            field=models.CharField(blank=True, choices=[('review', 'Review'), ('suture_removal', 'Suture Removal'), ('report_check', 'Report Check'), ('emergency', 'If Symptoms Worsen')], max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='abha_address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='abha_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_proof_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
