# Generated by Django 5.2.6 on 2026-03-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0040_consultation_created_at_consultation_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='dicom_instance_id',
            field=models.CharField(blank=True, help_text='Orthanc DICOM instance ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='is_dicom',
            field=models.BooleanField(default=False, help_text='True if stored in Orthanc DICOM server'),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medical_images/'),
        ),
    ]
