# Generated by Django 5.2.6 on 2026-04-01 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0041_medicalimage_dicom_instance_id_medicalimage_is_dicom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expense_head', models.CharField(choices=[('Civil Work', 'Civil Work'), ('Cement', 'Cement'), ('Steel', 'Steel'), ('Bricks', 'Bricks'), ('Sand', 'Sand'), ('RCC', 'RCC'), ('Labour', 'Labour'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Tiles', 'Tiles'), ('Granite', 'Granite'), ('Paint', 'Paint'), ('Doors', 'Doors'), ('Windows', 'Windows'), ('Aluminium', 'Aluminium'), ('False Ceiling', 'False Ceiling'), ('OT Construction', 'OT Construction'), ('Labour Room Construction', 'Labour Room Construction'), ('Reception Work', 'Reception Work'), ('Ward Work', 'Ward Work'), ('Fire Safety', 'Fire Safety'), ('Lift', 'Lift'), ('AC Ducting', 'AC Ducting'), ('Furniture', 'Furniture'), ('Misc', 'Misc')], max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('area_location', models.CharField(blank=True, choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Reception', 'Reception'), ('OPD', 'OPD'), ('OT', 'OT'), ('Labour Room', 'Labour Room'), ('Ward', 'Ward'), ('Private Room', 'Private Room'), ('ICU', 'ICU'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Lab'), ('X-Ray', 'X-Ray'), ('Staircase', 'Staircase'), ('Terrace', 'Terrace'), ('Toilet', 'Toilet'), ('Front Elevation', 'Front Elevation'), ('Parking', 'Parking'), ('General Building', 'General Building')], max_length=100, null=True)),
                ('vendor_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit', 'Credit')], max_length=50, null=True)),
                ('paid_by', models.CharField(blank=True, choices=[('Partner 1', 'Partner 1'), ('Partner 2', 'Partner 2'), ('Partner 3', 'Partner 3'), ('Company', 'Company'), ('Site Supervisor', 'Site Supervisor')], max_length=50, null=True)),
                ('paid_from', models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Company', 'Company'), ('Cash Box', 'Cash Box'), ('Bank', 'Bank')], max_length=50, null=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, choices=[('Partner 1', 'Partner 1'), ('Partner 2', 'Partner 2'), ('Partner 3', 'Partner 3'), ('All 3', 'All 3')], max_length=50, null=True)),
                ('work_status', models.CharField(blank=True, choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Partial', 'Partial')], max_length=20, null=True)),
                ('material_received', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=20, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('Tax Invoice', 'Tax Invoice'), ('Estimate', 'Estimate'), ('Cash Memo', 'Cash Memo'), ('Quotation', 'Quotation'), ('NA', 'NA')], max_length=50, null=True)),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='construction_expenses/bills/')),
                ('site_photo', models.ImageField(blank=True, null=True, upload_to='construction_expenses/site_photos/')),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='construction_expenses/quotations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Construction Expense',
                'verbose_name_plural': 'Construction Expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_head', models.CharField(choices=[('Civil Work', 'Civil Work'), ('Cement', 'Cement'), ('Steel', 'Steel'), ('Bricks', 'Bricks'), ('Sand', 'Sand'), ('RCC', 'RCC'), ('Labour', 'Labour'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Tiles', 'Tiles'), ('Granite', 'Granite'), ('Paint', 'Paint'), ('Doors', 'Doors'), ('Windows', 'Windows'), ('Aluminium', 'Aluminium'), ('False Ceiling', 'False Ceiling'), ('OT Construction', 'OT Construction'), ('Labour Room Construction', 'Labour Room Construction'), ('Reception Work', 'Reception Work'), ('Ward Work', 'Ward Work'), ('Fire Safety', 'Fire Safety'), ('Lift', 'Lift'), ('AC Ducting', 'AC Ducting'), ('Furniture', 'Furniture'), ('Misc', 'Misc')], max_length=100, unique=True)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Expense Budget',
                'verbose_name_plural': 'Expense Budgets',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('work_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('partner_name', models.CharField(choices=[('Partner 1', 'Partner 1'), ('Partner 2', 'Partner 2'), ('Partner 3', 'Partner 3'), ('Company', 'Company'), ('Site Supervisor', 'Site Supervisor')], max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_for', models.CharField(max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Credit', 'Credit')], max_length=50, null=True)),
                ('reimbursed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], default='No', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('expense_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.constructionexpense')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='constructionexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.vendor'),
        ),
    ]
