# Generated by Django 5.2.6 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0042_constructionexpense_expensebudget_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionexpense',
            name='approved_by',
            field=models.CharField(blank=True, choices=[('Dr. Pratap Senecha', 'Dr. Pratap Senecha'), ('Mr. Lumbaram', 'Mr. Lumbaram'), ('Mr. Poonaram', 'Mr. Poonaram'), ('All 3', 'All 3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='constructionexpense',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('Dr. Pratap Senecha', 'Dr. Pratap Senecha'), ('Mr. Lumbaram', 'Mr. Lumbaram'), ('Mr. Poonaram', 'Mr. Poonaram'), ('Company', 'Company'), ('Site Supervisor', 'Site Supervisor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpayment',
            name='partner_name',
            field=models.CharField(choices=[('Dr. Pratap Senecha', 'Dr. Pratap Senecha'), ('Mr. Lumbaram', 'Mr. Lumbaram'), ('Mr. Poonaram', 'Mr. Poonaram'), ('Company', 'Company'), ('Site Supervisor', 'Site Supervisor')], max_length=50),
        ),
    ]
