# Generated by Django 5.2.6 on 2026-04-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0044_alter_constructionexpense_expense_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usgreport',
            name='appendicolith',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='appendix_diameter',
            field=models.CharField(blank=True, help_text='mm', max_length=50),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='appendix_noncompressible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='appendix_periappendiceal_fluid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='appendix_probe_tenderness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='appendix_visualized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='bladder_calculus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='bladder_internal_echoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='bladder_mass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='bladder_state',
            field=models.CharField(blank=True, help_text='e.g. Well distended / Partially filled / Empty', max_length=50),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='bladder_wall_thick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='cbd_dilated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='colitis_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='colitis_site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='collapsed_distal_bowel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='dilated_bowel_loops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='fibroid_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='fibroid_site',
            field=models.CharField(blank=True, help_text='e.g. Anterior / Posterior / Fundal', max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='fibroid_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='fibroid_type',
            field=models.CharField(blank=True, help_text='e.g. Intramural / Subserosal / Submucosal', max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gaseous_bowel_loops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_calculi_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_calculi_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_contracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_distended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_pericholecystic_fluid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_probe_tenderness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_sludge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='gb_wall_thick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_bowel_loops',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_cough_impulse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_defect_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_irreducible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_omentum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_reducible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_side',
            field=models.CharField(blank=True, help_text='Right / Left / Bilateral', max_length=20),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='hernia_type',
            field=models.CharField(blank=True, help_text='e.g. Inguinal / Umbilical / Incisional / Femoral', max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ibs_suggestion',
            field=models.BooleanField(default=False, verbose_name='IBS Suggestion'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='inflamed_fat',
            field=models.BooleanField(default=False, verbose_name='Inflamed Periappendiceal Fat'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='liver_cyst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='liver_focal_lesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='liver_ihbr_dilated',
            field=models.BooleanField(default=False, verbose_name='IHBR Dilated'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='liver_mass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_cyst_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_cyst_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_cyst_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_cyst_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_hydroureter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_hydroureteronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_mild_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_moderate_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_severe_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_stone_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_stone_site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lk_stone_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lo_bulky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lo_cyst_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lo_cyst_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lo_cyst_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lo_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='lo_volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='pid_changes',
            field=models.BooleanField(default=False, verbose_name='PID Changes'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='prostate_echotexture',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='prostate_median_lobe',
            field=models.BooleanField(default=False, help_text='Median lobe hypertrophy'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='prostate_volume',
            field=models.CharField(blank=True, help_text='Volume in cc/ml', max_length=50),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='prostatomegaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='pvrv',
            field=models.CharField(blank=True, max_length=50, verbose_name='Post-Void Residual Volume (ml)'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_cyst_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_cyst_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_cyst_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_cyst_type',
            field=models.CharField(blank=True, help_text='e.g. Simple / Complex', max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_hydroureter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_hydroureteronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_mild_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_moderate_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_severe_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_stone_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_stone_site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='rk_stone_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ro_bulky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ro_cyst_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ro_cyst_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ro_cyst_type',
            field=models.CharField(blank=True, help_text='e.g. Simple / Hemorrhagic / Dermoid / Endometrioma', max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ro_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ro_volume',
            field=models.CharField(blank=True, help_text='Volume in cc', max_length=50),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='sbo_present',
            field=models.BooleanField(default=False, verbose_name='Small Bowel Obstruction'),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='spleen_cyst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='spleen_lesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='splenomegaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='to_and_fro_peristalsis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ureteric_hydronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ureteric_hydroureter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ureteric_hydroureteronephrosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ureteric_side',
            field=models.CharField(blank=True, help_text='Right / Left / Bilateral', max_length=20),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ureteric_site',
            field=models.CharField(blank=True, help_text='e.g. VUJ / PUJ / mid-ureter', max_length=200),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='ureteric_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usgreport',
            name='uterus_myometrium',
            field=models.CharField(blank=True, help_text='e.g. Homogeneous / Heterogeneous', max_length=200),
        ),
    ]
