# Generated by Django 5.2.6 on 2026-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0045_usgreport_appendicolith_usgreport_appendix_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
