# Generated by Django 5.2.6 on 2026-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0047_prescriptiontemplate_prescriptiontemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='generic_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
