# Generated by Django 5.2.6 on 2026-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0048_drugmaster_generic_name_alter_drugmaster_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diet_advice',
            field=models.TextField(blank=True),
        ),
    ]
