# Generated by Django 5.2.6 on 2026-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0049_consultation_diet_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='custom_investigations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionexpense',
            name='area_location',
            field=models.CharField(blank=True, choices=[('Soil Removal / Excavation', 'Soil Removal / Excavation'), ('Raft Foundation', 'Raft Foundation'), ('PCC Work', 'PCC Work'), ('RCC Work', 'RCC Work'), ('Basement', 'Basement'), ('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor'), ('Terrace', 'Terrace'), ('Staircase', 'Staircase'), ('Reception', 'Reception'), ('OPD', 'OPD'), ('OT', 'OT'), ('Labour Room', 'Labour Room'), ('Ward', 'Ward'), ('Private Room', 'Private Room'), ('ICU', 'ICU'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Lab'), ('X-Ray', 'X-Ray'), ('Toilet', 'Toilet'), ('Parking', 'Parking'), ('Front Elevation', 'Front Elevation'), ('General Building', 'General Building')], max_length=100, null=True),
        ),
    ]
