# Generated by Django 5.2.6 on 2026-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0050_consultation_custom_investigations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='sort_order',
            field=models.IntegerField(default=99),
        ),
    ]
