# Generated by Django 5.2.6 on 2026-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0051_drugmaster_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='default_dose',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='default_duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='default_frequency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='default_instructions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
