# Generated by Django 5.2.6 on 2026-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0052_drugmaster_default_dose_drugmaster_default_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='icd_codes',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='hms.icdcode'),
        ),
    ]
