# Generated by Django 5.2.6 on 2026-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0054_partner_partnerdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='procedures_performed',
            field=models.TextField(blank=True),
        ),
    ]
