# Generated by Django 5.2.6 on 2026-08-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0055_consultation_procedures_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmaster',
            name='atc_code',
            field=models.CharField(blank=True, default='', help_text="WHO ATC code e.g. 'N02BE01' for Paracetamol", max_length=10),
        ),
    ]
