# Generated by Django 5.2.6 on 2026-08-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0056_drugmaster_atc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDSymptomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_history', to='hms.ipdadmission')),
            ],
            options={
                'verbose_name': 'IPD Symptom Log',
                'verbose_name_plural': 'IPD Symptom History Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
