# Generated by Django 5.2.6 on 2026-08-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0057_ipdsymptomhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDTreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_plan', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_history', to='hms.ipdadmission')),
            ],
            options={
                'verbose_name': 'IPD Treatment Log',
                'verbose_name_plural': 'IPD Treatment History Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
