# Generated by Django 5.2.6 on 2026-08-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0058_ipdtreatmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdmedication',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_medications', to='hms.drugmaster'),
        ),
    ]
