# Generated by Django 5.2.6 on 2026-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0059_ipdmedication_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='atc_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
