# Generated by Django 5.2.6 on 2026-08-18 11:43

import re

import django.core.validators
from django.db import migrations, models

ATC_RE = re.compile(r'^[A-Za-z][A-Za-z0-9]*$')


def clear_bogus_atc_codes(apps, schema_editor):
    """
    Real ATC codes always start with a letter (e.g. 'N02BE01'). Some
    DrugMaster/Prescription rows had drug-strength values (e.g. '250+10mg')
    mistakenly saved into atc_code, which get displayed as if they were
    real ATC codes. Blank those out rather than show wrong data.
    """
    DrugMaster = apps.get_model('hms', 'DrugMaster')
    Prescription = apps.get_model('hms', 'Prescription')
    for Model in (DrugMaster, Prescription):
        for obj in Model.objects.exclude(atc_code='').exclude(atc_code__isnull=True):
            if not ATC_RE.match(obj.atc_code):
                obj.atc_code = ''
                obj.save(update_fields=['atc_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0060_prescription_atc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmaster',
            name='atc_code',
            field=models.CharField(blank=True, default='', help_text="WHO ATC code e.g. 'N02BE01' for Paracetamol", max_length=10, validators=[django.core.validators.RegexValidator(message="Enter a valid ATC code (e.g. 'N02BE01'), not a drug strength.", regex='^[A-Za-z][A-Za-z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='atc_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid ATC code (e.g. 'N02BE01'), not a drug strength.", regex='^[A-Za-z][A-Za-z0-9]*$')]),
        ),
        migrations.RunPython(clear_bogus_atc_codes, migrations.RunPython.noop),
    ]
