# Generated by Django 5.2.6 on 2026-08-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0062_backfill_drugmaster_atc_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationbill',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_bills', to='hms.ipdadmission'),
        ),
    ]
