# Generated by Django 5.2.6 on 2026-08-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0063_investigationbill_admission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdprogressnote',
            options={'ordering': ['-date_time']},
        ),
    ]
