# Generated by Django 5.2.6 on 2026-08-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0064_alter_ipdprogressnote_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDDischargeMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_medications', to='hms.ipdadmission')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipd_discharge_medications', to='hms.drugmaster')),
            ],
        ),
    ]
