# Generated by Django 5.2.6 on 2026-08-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0065_ipddischargemedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='discharge_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='follow_up_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='general_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='local_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='treatment_on_discharge',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DischargeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Any')], default='U', max_length=1)),
                ('diagnosis', models.TextField(blank=True)),
                ('chief_complaints', models.TextField(blank=True)),
                ('general_examination', models.TextField(blank=True)),
                ('local_examination', models.TextField(blank=True)),
                ('operation_notes', models.TextField(blank=True)),
                ('course_in_hospital', models.TextField(blank=True)),
                ('treatment_on_discharge', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['procedure_name', 'gender'],
                'unique_together': {('procedure_name', 'gender')},
            },
        ),
    ]
