# Generated by Django 5.2.6 on 2026-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0067_seed_discharge_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='past_history',
            field=models.ManyToManyField(blank=True, to='hms.pasthistory'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='surgical_history',
            field=models.ManyToManyField(blank=True, to='hms.surgicalhistory'),
        ),
    ]
