# Generated by Django 5.2.6 on 2026-08-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0069_seed_past_surgical_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.consultation')),
                ('surgical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.surgicalhistory')),
            ],
            options={
                'unique_together': {('consultation', 'surgical_history')},
            },
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='surgical_history',
        ),
        migrations.AddField(
            model_name='consultation',
            name='surgical_history',
            field=models.ManyToManyField(blank=True, through='hms.ConsultationSurgicalHistory', to='hms.surgicalhistory'),
        ),
    ]
