# Generated by Django 5.2.6 on 2026-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0070_consultationsurgicalhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='surgery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='surgical_history',
        ),
        migrations.DeleteModel(
            name='ConsultationSurgicalHistory',
        ),
        migrations.AddField(
            model_name='consultation',
            name='surgical_history',
            field=models.ManyToManyField(blank=True, to='hms.surgicalhistory'),
        ),
    ]
