# Generated by Django 5.2.6 on 2026-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0073_seed_advice_diet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_hb',
            field=models.CharField(blank=True, max_length=30, verbose_name='Hb'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_hbsag',
            field=models.CharField(blank=True, max_length=30, verbose_name='HbsAg'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_hiv',
            field=models.CharField(blank=True, max_length=30, verbose_name='HIV'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_platelet_count',
            field=models.CharField(blank=True, max_length=30, verbose_name='Platelet Count'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_rbs',
            field=models.CharField(blank=True, max_length=30, verbose_name='RBS (mg/dl)'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_tlc',
            field=models.CharField(blank=True, max_length=30, verbose_name='TLC'),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='inv_usg',
            field=models.CharField(blank=True, max_length=100, verbose_name='USG'),
        ),
    ]
