# Generated by Django 5.2.6 on 2026-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0074_ipdadmission_inv_hb_ipdadmission_inv_hbsag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icdcode',
            options={'ordering': ['-sort_order', 'code']},
        ),
        migrations.AddField(
            model_name='icdcode',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
