# Generated by Django 5.2.6 on 2026-08-24 04:39

from django.db import migrations, models


def backfill_sort_order(apps, schema_editor):
    # rows still at the old default (0) need to move to the new default (9999)
    ICDCode = apps.get_model('hms', 'ICDCode')
    ICDCode.objects.filter(sort_order=0).update(sort_order=9999)


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0075_alter_icdcode_options_icdcode_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icdcode',
            options={'ordering': ['sort_order', 'code']},
        ),
        migrations.AlterField(
            model_name='icdcode',
            name='sort_order',
            field=models.IntegerField(blank=True, default=9999, null=True),
        ),
        migrations.RunPython(backfill_sort_order, migrations.RunPython.noop),
    ]
