# Generated by Django 5.2.6 on 2026-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0076_alter_icdcode_options_alter_icdcode_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdcode',
            name='category',
            field=models.CharField(blank=True, choices=[('post_op', 'Post-op'), ('medical', 'Medical'), ('surgical', 'Surgical'), ('gynecology', 'Gynecology'), ('orthopedics', 'Orthopedics'), ('chest', 'Chest'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('urology', 'Urology')], default='', max_length=20),
        ),
    ]
