# Generated by Django 5.2.6 on 2026-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0079_seed_villages'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='lama_attendant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_attendant_relation',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_consent_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_consent_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lama_signed_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
