# Generated by Django 5.2.6 on 2026-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0080_consultation_lama_attendant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='quick_lab_values',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
