# Generated by Django 5.2.6 on 2026-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0081_consultation_quick_lab_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_investigation_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ai_probable_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ai_required_investigations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='usg_findings',
            field=models.TextField(blank=True),
        ),
    ]
