# Generated by Django 5.2.6 on 2026-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0085_rename_chest_xray'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='custom_past_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='custom_signs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='custom_surgical_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consultation',
            name='custom_symptoms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
