# Generated by Django 5.2.6 on 2026-08-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0086_consultation_custom_past_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='custom_past_history',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='custom_surgical_history',
        ),
    ]
