# Generated by Django 5.2.6 on 2026-08-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0087_remove_consultation_custom_past_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationparameter',
            name='method_description',
            field=models.TextField(blank=True, help_text="Full descriptive method sentence for the printed report, e.g. 'Hexokinase / Enzymatic method using glucose-6-phosphate dehydrogenase coupled reaction.' Falls back to 'method' if blank."),
        ),
    ]
