# Generated by Django 5.2.6 on 2026-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0093_regroup_lft_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='referral_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referral_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referral_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referral_urgency',
            field=models.CharField(blank=True, choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], max_length=20),
        ),
    ]
