# Generated by Django 5.2.6 on 2026-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0094_consultation_referral_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='referral_letter_text',
            field=models.TextField(blank=True),
        ),
    ]
