# Generated by Django 5.2.6 on 2026-09-04 14:14

import django.core.validators
import django.db.models.deletion
import hms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0095_consultation_referral_letter_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hms.models.construction_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm', '3gp', 'jpg', 'jpeg', 'png', 'webp', 'heic'])])),
                ('media_type', models.CharField(blank=True, choices=[('video', 'Video'), ('photo', 'Photo')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Construction Media',
                'verbose_name_plural': 'Construction Media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
