# Generated by Django 5.2.6 on 2026-09-04 14:30

import django.core.validators
import hms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0096_constructionmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionmedia',
            name='file',
            field=models.FileField(upload_to=hms.models.construction_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm', '3gp', 'jpg', 'jpeg', 'png', 'webp', 'heic', 'pdf', 'doc', 'docx', 'dwg', 'dxf'])]),
        ),
        migrations.AlterField(
            model_name='constructionmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('photo', 'Photo'), ('document', 'Document')], max_length=10),
        ),
    ]
