# Generated by Django 5.2.6 on 2026-09-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0097_alter_constructionmedia_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('investigation', 'Investigation Referral'), ('treatment', 'Treatment Referral')], default='investigation', max_length=20),
        ),
    ]
