# Generated by Django 5.2.6 on 2026-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0098_consultation_referral_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ['sort_order', 'category__dept_code', 'name']},
        ),
        migrations.AlterModelOptions(
            name='sign',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='investigation',
            name='sort_order',
            field=models.IntegerField(blank=True, default=9999),
        ),
        migrations.AddField(
            model_name='sign',
            name='sort_order',
            field=models.IntegerField(blank=True, default=9999),
        ),
        migrations.AddField(
            model_name='symptom',
            name='sort_order',
            field=models.IntegerField(blank=True, default=9999),
        ),
    ]
