# Generated by Django 5.2.6 on 2026-09-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0099_alter_investigation_options_alter_sign_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpNotePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
