# Generated by Django 5.2.6 on 2026-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0101_seed_followup_note_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='ipd_treatment',
            field=models.TextField(blank=True, help_text='Inpatient Medication Chart narrative — IV/inpatient treatment given during the stay'),
        ),
    ]
