# Generated by Django 5.2.6 on 2026-09-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0102_ipdadmission_ipd_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdtreatmenthistory',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.CreateModel(
            name='IPDProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('anaesthesia_type', models.CharField(choices=[('General', 'General'), ('Spinal', 'Spinal'), ('Local', 'Local'), ('Regional', 'Regional'), ('Sedation', 'Sedation')], max_length=20)),
                ('procedure_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='hms.ipdadmission')),
            ],
            options={
                'ordering': ['-procedure_date', '-recorded_at'],
            },
        ),
    ]
