# Generated by Django 5.2.6 on 2026-09-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0103_alter_ipdtreatmenthistory_options_ipdprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='certificate_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='consultation',
            name='certificate_reason',
            field=models.CharField(blank=True, choices=[('post_procedure', 'Post-Procedure Rest'), ('illness', 'Illness / Unfit for Duty'), ('fitness', 'Fitness Certificate'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='certificate_reason_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultation',
            name='certificate_text',
            field=models.TextField(blank=True),
        ),
    ]
