# Generated by Django 5.2.6 on 2026-09-14 04:33

import django.db.models.deletion
import hms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0105_remove_usgreport_additional_findings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TPAImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mapping', models.JSONField(default=dict, help_text="{'target_field': 'Excel column header', ...}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TPAScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('scheme_type', models.CharField(choices=[('private', 'Private/Corporate TPA (Insurance)'), ('government', 'Government Scheme (MAA Yojana / Ayushman Bharat)')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TPA / Scheme',
                'verbose_name_plural': 'TPA / Schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TPAImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tpa_imports/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('mapping', 'Awaiting Column Mapping'), ('done', 'Completed'), ('reverted', 'Reverted'), ('failed', 'Failed')], default='mapping', max_length=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpa_batches_reverted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TPA Import Batch',
                'verbose_name_plural': 'TPA Import Batches',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='TPAPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name_raw', models.CharField(blank=True, default='', help_text='Patient name as it appeared on an import row, kept until linked to a UHID.', max_length=150)),
                ('is_draft', models.BooleanField(default=False, help_text='Auto-created from an unmatched import row -- needs staff to link the correct UHID.')),
                ('scheme_type', models.CharField(choices=[('private', 'Private/Corporate TPA (Insurance)'), ('government', 'Government Scheme (MAA Yojana / Ayushman Bharat)')], max_length=12)),
                ('scheme_name_raw', models.CharField(blank=True, default='', help_text="Scheme/TPA name as imported, kept if it didn't match a known scheme.", max_length=150)),
                ('policy_no', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Policy No. / MAA-Yojana Beneficiary ID')),
                ('tid_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Pre-auth / TID Number')),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('package_code', models.CharField(blank=True, default='', max_length=100)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('query_raised', 'Query Raised'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpa_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpa_cases', to='hms.patient')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='hms.tpascheme')),
            ],
            options={
                'verbose_name': 'TPA Patient',
                'verbose_name_plural': 'TPA Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TPAImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('match_type', models.CharField(choices=[('tid', 'Matched by TID'), ('policy_name', 'Matched by Policy No. + Patient Name'), ('none', 'No match')], default='none', max_length=15)),
                ('action', models.CharField(choices=[('updated', 'Updated existing record'), ('created', 'Created new draft record'), ('skipped', 'Skipped -- no match'), ('error', 'Error')], max_length=10)),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text="{'field': {'before': ..., 'after': ...}, ...} -- used to trace/revert a bad import.")),
                ('error_message', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='hms.tpaimportbatch')),
                ('tpa_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='hms.tpapatient')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='TPADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('preauth_letter', 'Pre-auth Letter'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=hms.models.tpa_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tpa_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hms.tpapatient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
