# Generated by Django 5.2.6 on 2026-09-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0106_tpaimportmapping_tpascheme_tpaimportbatch_tpapatient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaimportbatch',
            name='scheme_type',
            field=models.CharField(choices=[('private', 'Private/Corporate TPA (Insurance)'), ('government', 'Government Scheme (MAA Yojana / Ayushman Bharat)')], default='government', max_length=12),
        ),
    ]
