# Generated by Django 5.2.6 on 2026-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0107_tpaimportbatch_scheme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpascheme',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='tpascheme',
            constraint=models.UniqueConstraint(fields=('name', 'scheme_type'), name='unique_tpa_scheme_name_per_type'),
        ),
    ]
