# Generated by Django 5.2.6 on 2026-09-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0108_alter_tpascheme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='past_history_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
