# Generated by Django 5.2.6 on 2026-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0109_consultation_past_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='USGImpressionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('liver_gallbladder', '1. Liver and Gall Bladder'), ('kidney', '2. Kidney'), ('ureter_bladder_prostate', '3. Ureter, Bladder and Prostate'), ('uterus_ovary', '4. Uterus and Ovary'), ('misc', '5. Miscellaneous')], default='misc', max_length=30)),
                ('sort_order', models.IntegerField(default=9999)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'USG Impression Option',
                'verbose_name_plural': 'USG Impression Options',
                'ordering': ['category', 'sort_order', 'text'],
            },
        ),
    ]
