# Generated by Django 5.2.6 on 2026-09-14 10:27

from django.db import migrations

SEED_DATA = {
    "liver_gallbladder": [
        "Hepatomegaly",
        "Fatty Liver - Grade I",
        "Cholelithiasis",
        "Acute Calculous Cholecystitis",
        "Chronic Calculous Cholecystitis",
    ],
    "kidney": [
        "Right Renal Calculus without Hydronephrosis",
        "Left Renal Calculus without Hydronephrosis",
        "Bilateral Renal Calculi without Hydronephrosis",
        "Right Renal Calculus with Hydronephrosis",
        "Left Renal Calculus with Hydronephrosis",
        "Simple Renal Cyst",
    ],
    "ureter_bladder_prostate": [
        "Right Ureteric Calculus with Hydroureteronephrosis",
        "Left Ureteric Calculus with Hydroureteronephrosis",
        "Cystitis",
        "Prostatomegaly without Significant Post-Void Residual Urine",
        "Prostatomegaly with Significant Post-Void Residual Urine",
        "Prostatomegaly with Thick-Walled Urinary Bladder",
        "Prostatomegaly with Features of Bladder Outlet Obstruction",
        "Urinary Bladder Calculus (Vesicle Calculus)",
        "Urinary Tract Infection (UTI)",
    ],
    "uterus_ovary": [
        "Pelvic Inflammatory Disease (PID)",
        "Chronic Cervicitis",
        "Fibroid Uterus",
        "Right Ovarian Cyst",
        "Left Ovarian Cyst",
    ],
    "misc": [
        "Gastritis",
        "Colitis",
        "Typhilitis",
        "Acute Appendicitis",
        "Sub acute Appendicitis",
        "Mesenteric Lymphadenitis",
        "Splenomegaly",
    ],
}


def seed_options(apps, schema_editor):
    USGImpressionOption = apps.get_model("hms", "USGImpressionOption")
    for category, items in SEED_DATA.items():
        for order, text in enumerate(items, start=1):
            USGImpressionOption.objects.get_or_create(
                text=text, category=category, defaults={"sort_order": order}
            )


def remove_options(apps, schema_editor):
    USGImpressionOption = apps.get_model("hms", "USGImpressionOption")
    all_texts = [t for items in SEED_DATA.values() for t in items]
    USGImpressionOption.objects.filter(text__in=all_texts).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0110_usgimpressionoption'),
    ]

    operations = [
        migrations.RunPython(seed_options, remove_options),
    ]
