# Generated by Django 5.2.6 on 2026-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0111_seed_usg_impression_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. MBBS, MS -- printed on report signature lines', max_length=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(blank=True, help_text='e.g. RMC No-27994 -- printed on report signature lines', max_length=50),
        ),
    ]
