# Generated by Django 5.2.6 on 2026-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0112_doctor_qualification_doctor_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='absence_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='absence_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='certificate_part',
            field=models.CharField(blank=True, choices=[('A', 'Part A — Sickness / Leave'), ('B', 'Part B — Fitness'), ('both', 'Both Parts')], max_length=6),
        ),
        migrations.AddField(
            model_name='consultation',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='days_absent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='fitness_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='place_of_examination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sickness_diagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
