# Generated by Django 5.2.6 on 2026-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0113_consultation_absence_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='scribe_raw_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scribe_structured_note',
            field=models.TextField(blank=True),
        ),
    ]
