# Generated by Django 5.2.6 on 2026-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0114_consultation_scribe_raw_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpaimportbatch',
            name='merged_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tpaimportrow',
            name='action',
            field=models.CharField(choices=[('updated', 'Updated existing record'), ('created', 'Created new draft record'), ('merged', "Merged into another row's total (same TID)"), ('skipped', 'Skipped -- no match'), ('error', 'Error')], max_length=10),
        ),
    ]
