# Generated by Django 5.2.6 on 2026-09-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0115_tpaimportbatch_merged_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_anesthetist',
            field=models.BooleanField(default=True, help_text="Show this person in the OT 'Anesthetist' dropdown"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_assistant',
            field=models.BooleanField(default=True, help_text="Show this person in the OT 'Assistant' dropdown"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_surgeon',
            field=models.BooleanField(default=True, help_text="Show this person in the OT 'Surgeon' dropdown"),
        ),
    ]
