# Generated by Django 5.2.6 on 2026-09-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0116_doctor_is_anesthetist_doctor_is_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the WhatsApp appointment reminder was sent -- unset means not yet sent.', null=True),
        ),
    ]
