# Generated by Django 5.2.6 on 2026-09-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0117_appointment_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='discharge_message_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the WhatsApp discharge thank-you message was sent -- unset means not yet sent.', null=True),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='followup_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the WhatsApp follow-up-date reminder was sent -- unset means not yet sent.', null=True),
        ),
    ]
