# Generated by Django 5.2.6 on 2026-09-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0118_ipdadmission_discharge_message_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abdmcarecontext',
            name='pending_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='abdmcarecontext',
            name='hi_type',
            field=models.CharField(choices=[('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report (Lab/USG)'), ('OPConsultation', 'OPD Consultation'), ('DischargeSummary', 'Discharge Summary'), ('ImmunizationRecord', 'Immunization Record'), ('HealthDocumentRecord', 'Health Document Record'), ('WellnessRecord', 'Wellness Record')], default='OPConsultation', max_length=50),
        ),
        migrations.CreateModel(
            name='ABDMLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abha_address', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abdm_link_tokens', to='hms.patient')),
            ],
            options={
                'verbose_name': 'ABDM Link Token',
                'verbose_name_plural': 'ABDM Link Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
