# Generated by Django 5.2.6 on 2026-09-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0119_abdmcarecontext_pending_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABDMLinkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('link_reference', models.CharField(max_length=100, unique=True)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abdm_linking_sessions', to='hms.patient')),
            ],
            options={
                'verbose_name': 'ABDM Linking Session',
                'verbose_name_plural': 'ABDM Linking Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
