# Generated by Django 5.2.6 on 2026-09-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0120_abdmlinkingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABDMConsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hip_id', models.CharField(blank=True, max_length=100)),
                ('purpose_code', models.CharField(default='CAREMGT', max_length=50)),
                ('purpose_text', models.CharField(default='Care Management', max_length=255)),
                ('hi_types', models.JSONField(default=list)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_id_type', models.CharField(blank=True, max_length=50)),
                ('requester_id_value', models.CharField(blank=True, max_length=100)),
                ('requester_id_system', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('consent_request_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abdm_consent_requests', to='hms.patient')),
            ],
            options={
                'verbose_name': 'ABDM Consent Request (HIU)',
                'verbose_name_plural': 'ABDM Consent Requests (HIU)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABDMConsentArtefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=100, unique=True)),
                ('hip_id', models.CharField(blank=True, max_length=100)),
                ('hi_types', models.JSONField(default=list)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='FETCHING', max_length=20)),
                ('raw_artefact', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='hms.abdmconsentrequest')),
            ],
            options={
                'verbose_name': 'ABDM Consent Artefact (HIU)',
                'verbose_name_plural': 'ABDM Consent Artefacts (HIU)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABDMHealthInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('our_private_key', models.CharField(max_length=100)),
                ('our_public_key', models.CharField(max_length=600)),
                ('our_nonce', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('RECEIVED', 'Received'), ('FAILED', 'Failed')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hi_requests', to='hms.abdmconsentartefact')),
            ],
            options={
                'verbose_name': 'ABDM Health Information Request (HIU)',
                'verbose_name_plural': 'ABDM Health Information Requests (HIU)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABDMReceivedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_context_reference', models.CharField(max_length=100)),
                ('hi_status', models.CharField(default='OK', max_length=20)),
                ('fhir_bundle', models.TextField(blank=True)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('hi_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hms.abdmhealthinformationrequest')),
            ],
            options={
                'verbose_name': 'ABDM Received Record (HIU)',
                'verbose_name_plural': 'ABDM Received Records (HIU)',
                'ordering': ['-received_at'],
            },
        ),
    ]
