# Generated by Django 5.2.6 on 2026-09-25 09:38

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0121_abdmconsentrequest_abdmconsentartefact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABDMScanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('hip_id', models.CharField(blank=True, max_length=50)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('abha_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('abha_address', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('year_of_birth', models.CharField(blank=True, max_length=4)),
                ('month_of_birth', models.CharField(blank=True, max_length=2)),
                ('day_of_birth', models.CharField(blank=True, max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('patient_created', models.BooleanField(default=False)),
                ('token_number', models.CharField(blank=True, max_length=10)),
                ('token_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('DONE', 'Done')], default='WAITING', max_length=10)),
                ('on_share_sent', models.BooleanField(default=False)),
                ('on_share_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_shares', to='hms.patient')),
            ],
            options={
                'verbose_name': 'ABDM Scan & Share',
                'verbose_name_plural': 'ABDM Scan & Share',
                'ordering': ['-created_at'],
            },
        ),
    ]
