# Generated by Django 5.2.6 on 2026-09-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0122_abdmscanshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='drug',
            field=models.ForeignKey(blank=True, help_text='Drug Master entry doctors prescribe this as', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='hms.drugmaster'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, help_text='Units per strip/pack, e.g. 10 tablets'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='schedule',
            field=models.CharField(choices=[('OTC', 'OTC / Non-scheduled'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X')], default='OTC', max_length=3),
        ),
        migrations.AddField(
            model_name='stockin',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nursing', 'Nursing Staff'), ('laboratory', 'Laboratory'), ('reception', 'Reception'), ('pharmacy', 'Pharmacy')], default='reception', max_length=20),
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_mobile', models.CharField(blank=True, max_length=20)),
                ('doctor_name', models.CharField(blank=True, help_text='Prescriber, if not one of our doctors', max_length=150)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('FREE', 'Free of Cost')], default='CASH', max_length=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to='hms.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bills', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hms.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='hms.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_remaining', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='hms.inventoryitem')),
                ('stock_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='hms.stockin')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hms.pharmacybill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to='hms.inventoryitem')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_items', to='hms.prescription')),
                ('stock_out', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_bill_item', to='hms.stockout')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_sales', to='hms.stockbatch')),
            ],
        ),
        migrations.AddField(
            model_name='stockout',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='hms.stockbatch'),
        ),
    ]
