# Generated by Django 5.2.6 on 2026-09-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0123_pharmacy_dispensing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybill',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_bills', to='hms.ipdadmission'),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total refunded/credited through partial returns', max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacybillitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacybill',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('FREE', 'Free of Cost'), ('IPD', 'Charged to IPD bill')], default='CASH', max_length=10),
        ),
        migrations.CreateModel(
            name='PharmacyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='hms.pharmacybill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='hms.pharmacybillitem')),
                ('pharmacy_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hms.pharmacyreturn')),
            ],
        ),
    ]
