# Generated by Django 5.2.6 on 2026-09-25 13:08

from django.db import migrations, models


def backfill_prescribed_as(apps, schema_editor):
    PharmacyBillItem = apps.get_model("hms", "PharmacyBillItem")
    PharmacyBill = apps.get_model("hms", "PharmacyBill")
    for bi in PharmacyBillItem.objects.filter(prescription__isnull=False).select_related("prescription"):
        bi.prescribed_as = bi.prescription.medicine[:200]
        bi.save(update_fields=["prescribed_as"])
    # Existing OPD bills: treat the prescription as it stands now as "seen" at dispensing.
    for bill in PharmacyBill.objects.filter(consultation__isnull=False):
        bill.prescribed_snapshot = list(
            apps.get_model("hms", "Prescription").objects
            .filter(consultation_id=bill.consultation_id).values_list("medicine", flat=True)
        )
        bill.save(update_fields=["prescribed_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0124_pharmacy_ipd_and_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacybillitem',
            name='prescribed_as',
            field=models.CharField(blank=True, help_text='Prescribed medicine name at dispensing time', max_length=200),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='prescribed_snapshot',
            field=models.JSONField(blank=True, default=list, help_text="Medicines on the consultation's prescription when this bill was made"),
        ),
        migrations.RunPython(backfill_prescribed_as, migrations.RunPython.noop),
    ]
