# Generated by Django 5.2.6 on 2026-09-25 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0125_pharmacybillitem_prescribed_as'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='housekeeping',
            field=models.CharField(blank=True, choices=[('', 'Ready'), ('CLEANING', 'Cleaning'), ('BLOCKED', 'Blocked (maintenance)')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dischargebill',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_bill', to='hms.ipdadmission'),
        ),
        migrations.AddField(
            model_name='dischargebillitem',
            name='auto_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='discharge_override_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='discharged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipdadvance',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hms.ipdadmission'),
        ),
        migrations.AddField(
            model_name='ward',
            name='bed_charge_item',
            field=models.ForeignKey(blank=True, help_text='Per-day bed charge billed for a stay in this ward', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='hms.billitem'),
        ),
        migrations.AlterField(
            model_name='dischargebill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_bills', to='hms.patient'),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='status',
            field=models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled (entered in error)')], default='ADMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='BedStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_stays', to='hms.ipdadmission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='hms.bed')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='hms.ward')),
            ],
            options={
                'ordering': ['start', 'id'],
            },
        ),
    ]
